version: "3.7"

services: 
    tests:
        image: gmax079/practice:abftests
        container_name: abftests
        environment:
          WAIT_HOSTS: localhost:9000 # for wait tool
          WAIT_HOSTS_TIMEOUT: 10
        network_mode: "host"
