version: "3.7"

services:
    abf:
      image: gmax079/practice:abf
      container_name: abf
      environment:
        ABF_HOST: "0.0.0.0:9000"
        ABF_LOGIN_RATE: 10
        ABF_PASSWORD_RATE: 100
        ABF_IP_RATE: 1000
      ports:
        - "9000:9000"
