stages:
  - test
  - build
  - buildbautotests

unittest:
  stage: test
  image: golang:1.13.7
  script:
    - go get -u github.com/jstemmer/go-junit-report
    - make unittest | go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml
      
golangci-lint:
  stage: test
  image: golangci/golangci-lint
  script:
    - make check

buildapp:
  stage: build
  image: golang:1.13.7
  script:
    - make abf
  artifacts:
    paths:
      - cmd/abf/abf

buildautotests:
  stage: buildbautotests
  image: golang:1.13.7
  script:
    - make abftests
  artifacts:
    paths:
      - cmd/tests/tests
