stages:
  - test
  - build

unittest:
  stage: test
  image: golang:1.13.7
  script:
    - go get -u github.com/jstemmer/go-junit-report
    - make unittest | go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml

golangci-lint:
  stage: test
  image: golangci/golangci-lint
  script:
    - make check

buildall:
  stage: build
  image: golang:1.13.7
  script:
    - apt-get update -y && apt-get install unzip 
    - ./build/ci/install_protoc.sh
    - make all
    - cp cmd/abf/abf cmd/abf/config.json cmd/tests/tests .
  artifacts:
    paths:
      - abf
      - config.json
      - abfcli
      - tests
