stages:
  - intergration_tests

intergration_tests:
  stage: intergration_tests
  image: docker:19.03.6
  script:
    - apk add bash curl make unzip
    - ./build/ci/install_golang.sh
    - export PATH=/usr/local/go/bin:$PATH
    - ls -la /usr/local/go/bin
    - go version
    - ./build/ci/install_protoc.sh
    - make docker
    - make test
