stages:
  - intergration_tests

unittest:
  stage: test
  image: golang:1.13.7
  script:
    - go get -u github.com/jstemmer/go-junit-report
    - make unittest | go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml

golangci-lint:
  stage: test
  image: golangci/golangci-lint
  script:
    - make check

buildall:
  stage: build
  image: golang:1.13.7
  script:
    - apt-get update -y && apt-get install unzip 
    - ./build/ci/install_protoc.sh
    - make all

intergration_tests:
  stage: intergration_tests
  image: docker:19.03.6
  script:
    - apk add bash curl make unzip
    - ./build/ci/install_golang.sh
    - export PATH=/usr/local/go:$PATH
    - ls /usr/local/go
    - echo $PATH
    - ./build/ci/install_protoc.sh
    - make docker
    - make test
