stages:
  - test
  - autotests

unittest:
  stage: test
  image: golang:1.13.7
  script:
    - go get -u github.com/jstemmer/go-junit-report
    - make unittest | go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml

golangci-lint:
  stage: test
  image: golangci/golangci-lint
  script:
    - make check

integration_tests:
  stage: autotests
  image: ubuntu:18.04
  script:
    - make docker
    - make test
