stages:
  - test
  - build
  - autotests

unittest:
  stage: test
  image: golang:1.13.7
  script:
    - go get -u github.com/jstemmer/go-junit-report
    - make unittest | go-junit-report > report.xml
  artifacts:
    reports:
      junit: report.xml

golangci-lint:
  stage: test
  image: golangci/golangci-lint
  script:
    - make check

buildapp:
  stage: build
  image: golang:1.13.7
  script:
    - ./build/ci/install_protoc.sh
    - make abf
  artifacts:
    paths:
      - cmd/abf/abf

buildautotests:
  stage: build
  image: golang:1.13.7
  script:
    - make abftests
  artifacts:
    paths:
      - cmd/tests/tests

runautotests:
  stage: autotests
  image: ubuntu:18.04
  needs:
    - job: buildapp
      artifacts: true
    - job: buildautotests
      artifacts: true
  script:
      - ./build/ci/run_autotests.sh