// Code generated by protoc-gen-go. DO NOT EDIT.
// source: antibf.proto

package grpcapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckLoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLoginRequest) Reset()         { *m = CheckLoginRequest{} }
func (m *CheckLoginRequest) String() string { return proto.CompactTextString(m) }
func (*CheckLoginRequest) ProtoMessage()    {}
func (*CheckLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{0}
}

func (m *CheckLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLoginRequest.Unmarshal(m, b)
}
func (m *CheckLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLoginRequest.Marshal(b, m, deterministic)
}
func (m *CheckLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLoginRequest.Merge(m, src)
}
func (m *CheckLoginRequest) XXX_Size() int {
	return xxx_messageInfo_CheckLoginRequest.Size(m)
}
func (m *CheckLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLoginRequest proto.InternalMessageInfo

func (m *CheckLoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *CheckLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CheckLoginRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type CheckLoginResponse struct {
	Checked              bool     `protobuf:"varint,1,opt,name=checked,proto3" json:"checked,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLoginResponse) Reset()         { *m = CheckLoginResponse{} }
func (m *CheckLoginResponse) String() string { return proto.CompactTextString(m) }
func (*CheckLoginResponse) ProtoMessage()    {}
func (*CheckLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{1}
}

func (m *CheckLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLoginResponse.Unmarshal(m, b)
}
func (m *CheckLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLoginResponse.Marshal(b, m, deterministic)
}
func (m *CheckLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLoginResponse.Merge(m, src)
}
func (m *CheckLoginResponse) XXX_Size() int {
	return xxx_messageInfo_CheckLoginResponse.Size(m)
}
func (m *CheckLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLoginResponse proto.InternalMessageInfo

func (m *CheckLoginResponse) GetChecked() bool {
	if m != nil {
		return m.Checked
	}
	return false
}

func (m *CheckLoginResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ResetLoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetLoginRequest) Reset()         { *m = ResetLoginRequest{} }
func (m *ResetLoginRequest) String() string { return proto.CompactTextString(m) }
func (*ResetLoginRequest) ProtoMessage()    {}
func (*ResetLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{2}
}

func (m *ResetLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetLoginRequest.Unmarshal(m, b)
}
func (m *ResetLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetLoginRequest.Marshal(b, m, deterministic)
}
func (m *ResetLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetLoginRequest.Merge(m, src)
}
func (m *ResetLoginRequest) XXX_Size() int {
	return xxx_messageInfo_ResetLoginRequest.Size(m)
}
func (m *ResetLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetLoginRequest proto.InternalMessageInfo

func (m *ResetLoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ResetLoginRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ResetLoginResponse struct {
	Reseted              bool     `protobuf:"varint,1,opt,name=reseted,proto3" json:"reseted,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetLoginResponse) Reset()         { *m = ResetLoginResponse{} }
func (m *ResetLoginResponse) String() string { return proto.CompactTextString(m) }
func (*ResetLoginResponse) ProtoMessage()    {}
func (*ResetLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{3}
}

func (m *ResetLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetLoginResponse.Unmarshal(m, b)
}
func (m *ResetLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetLoginResponse.Marshal(b, m, deterministic)
}
func (m *ResetLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetLoginResponse.Merge(m, src)
}
func (m *ResetLoginResponse) XXX_Size() int {
	return xxx_messageInfo_ResetLoginResponse.Size(m)
}
func (m *ResetLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetLoginResponse proto.InternalMessageInfo

func (m *ResetLoginResponse) GetReseted() bool {
	if m != nil {
		return m.Reseted
	}
	return false
}

func (m *ResetLoginResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type AddWhiteListRequest struct {
	Ipmask               string   `protobuf:"bytes,1,opt,name=ipmask,proto3" json:"ipmask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWhiteListRequest) Reset()         { *m = AddWhiteListRequest{} }
func (m *AddWhiteListRequest) String() string { return proto.CompactTextString(m) }
func (*AddWhiteListRequest) ProtoMessage()    {}
func (*AddWhiteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{4}
}

func (m *AddWhiteListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWhiteListRequest.Unmarshal(m, b)
}
func (m *AddWhiteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWhiteListRequest.Marshal(b, m, deterministic)
}
func (m *AddWhiteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWhiteListRequest.Merge(m, src)
}
func (m *AddWhiteListRequest) XXX_Size() int {
	return xxx_messageInfo_AddWhiteListRequest.Size(m)
}
func (m *AddWhiteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWhiteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWhiteListRequest proto.InternalMessageInfo

func (m *AddWhiteListRequest) GetIpmask() string {
	if m != nil {
		return m.Ipmask
	}
	return ""
}

type AddWhiteListResponse struct {
	Added                bool     `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWhiteListResponse) Reset()         { *m = AddWhiteListResponse{} }
func (m *AddWhiteListResponse) String() string { return proto.CompactTextString(m) }
func (*AddWhiteListResponse) ProtoMessage()    {}
func (*AddWhiteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{5}
}

func (m *AddWhiteListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWhiteListResponse.Unmarshal(m, b)
}
func (m *AddWhiteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWhiteListResponse.Marshal(b, m, deterministic)
}
func (m *AddWhiteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWhiteListResponse.Merge(m, src)
}
func (m *AddWhiteListResponse) XXX_Size() int {
	return xxx_messageInfo_AddWhiteListResponse.Size(m)
}
func (m *AddWhiteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWhiteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddWhiteListResponse proto.InternalMessageInfo

func (m *AddWhiteListResponse) GetAdded() bool {
	if m != nil {
		return m.Added
	}
	return false
}

func (m *AddWhiteListResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type DeleteWhiteListRequest struct {
	Ipmask               string   `protobuf:"bytes,1,opt,name=ipmask,proto3" json:"ipmask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWhiteListRequest) Reset()         { *m = DeleteWhiteListRequest{} }
func (m *DeleteWhiteListRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteWhiteListRequest) ProtoMessage()    {}
func (*DeleteWhiteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{6}
}

func (m *DeleteWhiteListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWhiteListRequest.Unmarshal(m, b)
}
func (m *DeleteWhiteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWhiteListRequest.Marshal(b, m, deterministic)
}
func (m *DeleteWhiteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWhiteListRequest.Merge(m, src)
}
func (m *DeleteWhiteListRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteWhiteListRequest.Size(m)
}
func (m *DeleteWhiteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWhiteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWhiteListRequest proto.InternalMessageInfo

func (m *DeleteWhiteListRequest) GetIpmask() string {
	if m != nil {
		return m.Ipmask
	}
	return ""
}

type DeleteWhiteListResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWhiteListResponse) Reset()         { *m = DeleteWhiteListResponse{} }
func (m *DeleteWhiteListResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteWhiteListResponse) ProtoMessage()    {}
func (*DeleteWhiteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{7}
}

func (m *DeleteWhiteListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWhiteListResponse.Unmarshal(m, b)
}
func (m *DeleteWhiteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWhiteListResponse.Marshal(b, m, deterministic)
}
func (m *DeleteWhiteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWhiteListResponse.Merge(m, src)
}
func (m *DeleteWhiteListResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteWhiteListResponse.Size(m)
}
func (m *DeleteWhiteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWhiteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWhiteListResponse proto.InternalMessageInfo

func (m *DeleteWhiteListResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *DeleteWhiteListResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type AddBlackListRequest struct {
	Ipmask               string   `protobuf:"bytes,1,opt,name=ipmask,proto3" json:"ipmask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBlackListRequest) Reset()         { *m = AddBlackListRequest{} }
func (m *AddBlackListRequest) String() string { return proto.CompactTextString(m) }
func (*AddBlackListRequest) ProtoMessage()    {}
func (*AddBlackListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{8}
}

func (m *AddBlackListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBlackListRequest.Unmarshal(m, b)
}
func (m *AddBlackListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBlackListRequest.Marshal(b, m, deterministic)
}
func (m *AddBlackListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBlackListRequest.Merge(m, src)
}
func (m *AddBlackListRequest) XXX_Size() int {
	return xxx_messageInfo_AddBlackListRequest.Size(m)
}
func (m *AddBlackListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBlackListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBlackListRequest proto.InternalMessageInfo

func (m *AddBlackListRequest) GetIpmask() string {
	if m != nil {
		return m.Ipmask
	}
	return ""
}

type AddBlackListResponse struct {
	Added                bool     `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBlackListResponse) Reset()         { *m = AddBlackListResponse{} }
func (m *AddBlackListResponse) String() string { return proto.CompactTextString(m) }
func (*AddBlackListResponse) ProtoMessage()    {}
func (*AddBlackListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{9}
}

func (m *AddBlackListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBlackListResponse.Unmarshal(m, b)
}
func (m *AddBlackListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBlackListResponse.Marshal(b, m, deterministic)
}
func (m *AddBlackListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBlackListResponse.Merge(m, src)
}
func (m *AddBlackListResponse) XXX_Size() int {
	return xxx_messageInfo_AddBlackListResponse.Size(m)
}
func (m *AddBlackListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBlackListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBlackListResponse proto.InternalMessageInfo

func (m *AddBlackListResponse) GetAdded() bool {
	if m != nil {
		return m.Added
	}
	return false
}

func (m *AddBlackListResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type DeleteBlackListRequest struct {
	Ipmask               string   `protobuf:"bytes,1,opt,name=ipmask,proto3" json:"ipmask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlackListRequest) Reset()         { *m = DeleteBlackListRequest{} }
func (m *DeleteBlackListRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBlackListRequest) ProtoMessage()    {}
func (*DeleteBlackListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{10}
}

func (m *DeleteBlackListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlackListRequest.Unmarshal(m, b)
}
func (m *DeleteBlackListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlackListRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBlackListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlackListRequest.Merge(m, src)
}
func (m *DeleteBlackListRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBlackListRequest.Size(m)
}
func (m *DeleteBlackListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlackListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlackListRequest proto.InternalMessageInfo

func (m *DeleteBlackListRequest) GetIpmask() string {
	if m != nil {
		return m.Ipmask
	}
	return ""
}

type DeleteBlackListResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlackListResponse) Reset()         { *m = DeleteBlackListResponse{} }
func (m *DeleteBlackListResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBlackListResponse) ProtoMessage()    {}
func (*DeleteBlackListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eea75b880b143454, []int{11}
}

func (m *DeleteBlackListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlackListResponse.Unmarshal(m, b)
}
func (m *DeleteBlackListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlackListResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBlackListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlackListResponse.Merge(m, src)
}
func (m *DeleteBlackListResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBlackListResponse.Size(m)
}
func (m *DeleteBlackListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlackListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlackListResponse proto.InternalMessageInfo

func (m *DeleteBlackListResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *DeleteBlackListResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckLoginRequest)(nil), "grpcapi.CheckLoginRequest")
	proto.RegisterType((*CheckLoginResponse)(nil), "grpcapi.CheckLoginResponse")
	proto.RegisterType((*ResetLoginRequest)(nil), "grpcapi.ResetLoginRequest")
	proto.RegisterType((*ResetLoginResponse)(nil), "grpcapi.ResetLoginResponse")
	proto.RegisterType((*AddWhiteListRequest)(nil), "grpcapi.AddWhiteListRequest")
	proto.RegisterType((*AddWhiteListResponse)(nil), "grpcapi.AddWhiteListResponse")
	proto.RegisterType((*DeleteWhiteListRequest)(nil), "grpcapi.DeleteWhiteListRequest")
	proto.RegisterType((*DeleteWhiteListResponse)(nil), "grpcapi.DeleteWhiteListResponse")
	proto.RegisterType((*AddBlackListRequest)(nil), "grpcapi.AddBlackListRequest")
	proto.RegisterType((*AddBlackListResponse)(nil), "grpcapi.AddBlackListResponse")
	proto.RegisterType((*DeleteBlackListRequest)(nil), "grpcapi.DeleteBlackListRequest")
	proto.RegisterType((*DeleteBlackListResponse)(nil), "grpcapi.DeleteBlackListResponse")
}

func init() { proto.RegisterFile("antibf.proto", fileDescriptor_eea75b880b143454) }

var fileDescriptor_eea75b880b143454 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0x43, 0x09, 0x7f, 0xde, 0x09, 0xe1, 0x0d, 0x2b, 0xc1, 0xa6, 0x6a, 0x24, 0x3d, 0x79,
	0x91, 0x18, 0x3d, 0x79, 0x04, 0xc1, 0x0b, 0x9c, 0x1a, 0x8d, 0xe7, 0xd2, 0x0e, 0xb0, 0x01, 0xdb,
	0xb5, 0xbb, 0xc4, 0x2f, 0xec, 0x07, 0x31, 0xb4, 0xcb, 0x76, 0x4b, 0xdb, 0x58, 0xe3, 0xf1, 0xd9,
	0x99, 0x7d, 0xe6, 0x37, 0xd9, 0xa7, 0x85, 0x8e, 0x1b, 0x08, 0xba, 0x5c, 0x8d, 0x58, 0x14, 0x8a,
	0x90, 0xb4, 0xd6, 0x11, 0xf3, 0x5c, 0x46, 0xed, 0x57, 0xe8, 0x3d, 0x6d, 0xd0, 0xdb, 0x2e, 0xc2,
	0x35, 0x0d, 0x1c, 0xfc, 0xd8, 0x23, 0x17, 0xa4, 0x0f, 0x8d, 0xdd, 0x41, 0x9b, 0xb5, 0x61, 0xed,
	0xe6, 0x9f, 0x93, 0x08, 0x62, 0x41, 0x9b, 0xb9, 0x9c, 0x7f, 0x86, 0x91, 0x6f, 0x1a, 0x71, 0x41,
	0x69, 0xd2, 0x05, 0x83, 0x32, 0xb3, 0x1e, 0x9f, 0x1a, 0x94, 0xd9, 0xcf, 0x40, 0x74, 0x5b, 0xce,
	0xc2, 0x80, 0x23, 0x31, 0xa1, 0xe5, 0x1d, 0x4e, 0xd1, 0x8f, 0x9d, 0xdb, 0xce, 0x51, 0x92, 0x01,
	0x34, 0x23, 0x74, 0x79, 0x18, 0x48, 0x67, 0xa9, 0xec, 0x47, 0xe8, 0x39, 0xc8, 0x51, 0x54, 0xc0,
	0x4b, 0x10, 0x0c, 0x1d, 0x41, 0xbf, 0x9a, 0x22, 0x44, 0x87, 0xd3, 0x14, 0x41, 0xca, 0x52, 0x84,
	0x5b, 0x38, 0x1b, 0xfb, 0xfe, 0xdb, 0x86, 0x0a, 0x5c, 0x50, 0x2e, 0x8e, 0x10, 0x03, 0x68, 0x52,
	0xf6, 0xee, 0xf2, 0xad, 0xa4, 0x90, 0xca, 0x9e, 0x42, 0x3f, 0xdb, 0x2e, 0x07, 0xf7, 0xa1, 0xe1,
	0xfa, 0xbe, 0x1a, 0x9b, 0x88, 0xd2, 0xa1, 0x77, 0x30, 0x98, 0xe2, 0x0e, 0x05, 0x56, 0x9e, 0x3b,
	0x87, 0xf3, 0xdc, 0x8d, 0x74, 0x67, 0x3f, 0x2e, 0xa9, 0x9d, 0xa5, 0xfc, 0x61, 0xe7, 0xc9, 0xce,
	0xf5, 0xb6, 0xd5, 0x77, 0xd6, 0xda, 0xff, 0xb6, 0x73, 0xe5, 0xb9, 0x6a, 0xe7, 0xfc, 0xe8, 0x5f,
	0xef, 0x7c, 0xff, 0x55, 0x87, 0xee, 0x38, 0x10, 0x74, 0x12, 0xed, 0x05, 0xae, 0xc2, 0xc8, 0x43,
	0x32, 0x03, 0x48, 0x53, 0x4c, 0xac, 0x91, 0xfc, 0x68, 0x46, 0xb9, 0x2f, 0xc6, 0xba, 0x28, 0xac,
	0x49, 0x96, 0x19, 0x40, 0x9a, 0x44, 0xcd, 0x26, 0x97, 0x6c, 0xcd, 0xa6, 0x20, 0xba, 0x73, 0xe8,
	0xe8, 0xc9, 0x22, 0x97, 0xaa, 0xb9, 0x20, 0x9f, 0xd6, 0x55, 0x49, 0x55, 0x9a, 0xbd, 0xc0, 0xff,
	0x93, 0xb8, 0x90, 0x6b, 0x75, 0xa3, 0x38, 0x7a, 0xd6, 0xb0, 0xbc, 0x21, 0x83, 0xa8, 0x5e, 0x23,
	0x8b, 0x78, 0xfa, 0xac, 0x59, 0xc4, 0xfc, 0x13, 0x2a, 0xc4, 0xd4, 0xef, 0x14, 0x31, 0x67, 0x39,
	0x2c, 0x6f, 0x48, 0x5c, 0x97, 0xcd, 0xf8, 0x07, 0xf8, 0xf0, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x26,
	0xe6, 0x9e, 0x62, 0x10, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AntiBruteforceClient is the client API for AntiBruteforce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AntiBruteforceClient interface {
	CheckLogin(ctx context.Context, in *CheckLoginRequest, opts ...grpc.CallOption) (*CheckLoginResponse, error)
	ResetLogin(ctx context.Context, in *ResetLoginRequest, opts ...grpc.CallOption) (*ResetLoginResponse, error)
	AddWhiteList(ctx context.Context, in *AddWhiteListRequest, opts ...grpc.CallOption) (*AddWhiteListResponse, error)
	DeleteWhiteList(ctx context.Context, in *DeleteWhiteListRequest, opts ...grpc.CallOption) (*DeleteWhiteListResponse, error)
	AddBlackList(ctx context.Context, in *AddBlackListRequest, opts ...grpc.CallOption) (*AddBlackListResponse, error)
	DeleteBlackList(ctx context.Context, in *DeleteBlackListRequest, opts ...grpc.CallOption) (*DeleteBlackListResponse, error)
}

type antiBruteforceClient struct {
	cc *grpc.ClientConn
}

func NewAntiBruteforceClient(cc *grpc.ClientConn) AntiBruteforceClient {
	return &antiBruteforceClient{cc}
}

func (c *antiBruteforceClient) CheckLogin(ctx context.Context, in *CheckLoginRequest, opts ...grpc.CallOption) (*CheckLoginResponse, error) {
	out := new(CheckLoginResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.AntiBruteforce/CheckLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) ResetLogin(ctx context.Context, in *ResetLoginRequest, opts ...grpc.CallOption) (*ResetLoginResponse, error) {
	out := new(ResetLoginResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.AntiBruteforce/ResetLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) AddWhiteList(ctx context.Context, in *AddWhiteListRequest, opts ...grpc.CallOption) (*AddWhiteListResponse, error) {
	out := new(AddWhiteListResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.AntiBruteforce/AddWhiteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) DeleteWhiteList(ctx context.Context, in *DeleteWhiteListRequest, opts ...grpc.CallOption) (*DeleteWhiteListResponse, error) {
	out := new(DeleteWhiteListResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.AntiBruteforce/DeleteWhiteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) AddBlackList(ctx context.Context, in *AddBlackListRequest, opts ...grpc.CallOption) (*AddBlackListResponse, error) {
	out := new(AddBlackListResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.AntiBruteforce/AddBlackList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) DeleteBlackList(ctx context.Context, in *DeleteBlackListRequest, opts ...grpc.CallOption) (*DeleteBlackListResponse, error) {
	out := new(DeleteBlackListResponse)
	err := c.cc.Invoke(ctx, "/grpcapi.AntiBruteforce/DeleteBlackList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiBruteforceServer is the server API for AntiBruteforce service.
type AntiBruteforceServer interface {
	CheckLogin(context.Context, *CheckLoginRequest) (*CheckLoginResponse, error)
	ResetLogin(context.Context, *ResetLoginRequest) (*ResetLoginResponse, error)
	AddWhiteList(context.Context, *AddWhiteListRequest) (*AddWhiteListResponse, error)
	DeleteWhiteList(context.Context, *DeleteWhiteListRequest) (*DeleteWhiteListResponse, error)
	AddBlackList(context.Context, *AddBlackListRequest) (*AddBlackListResponse, error)
	DeleteBlackList(context.Context, *DeleteBlackListRequest) (*DeleteBlackListResponse, error)
}

// UnimplementedAntiBruteforceServer can be embedded to have forward compatible implementations.
type UnimplementedAntiBruteforceServer struct {
}

func (*UnimplementedAntiBruteforceServer) CheckLogin(ctx context.Context, req *CheckLoginRequest) (*CheckLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLogin not implemented")
}
func (*UnimplementedAntiBruteforceServer) ResetLogin(ctx context.Context, req *ResetLoginRequest) (*ResetLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetLogin not implemented")
}
func (*UnimplementedAntiBruteforceServer) AddWhiteList(ctx context.Context, req *AddWhiteListRequest) (*AddWhiteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWhiteList not implemented")
}
func (*UnimplementedAntiBruteforceServer) DeleteWhiteList(ctx context.Context, req *DeleteWhiteListRequest) (*DeleteWhiteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWhiteList not implemented")
}
func (*UnimplementedAntiBruteforceServer) AddBlackList(ctx context.Context, req *AddBlackListRequest) (*AddBlackListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBlackList not implemented")
}
func (*UnimplementedAntiBruteforceServer) DeleteBlackList(ctx context.Context, req *DeleteBlackListRequest) (*DeleteBlackListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBlackList not implemented")
}

func RegisterAntiBruteforceServer(s *grpc.Server, srv AntiBruteforceServer) {
	s.RegisterService(&_AntiBruteforce_serviceDesc, srv)
}

func _AntiBruteforce_CheckLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).CheckLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.AntiBruteforce/CheckLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).CheckLogin(ctx, req.(*CheckLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_ResetLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).ResetLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.AntiBruteforce/ResetLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).ResetLogin(ctx, req.(*ResetLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_AddWhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWhiteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).AddWhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.AntiBruteforce/AddWhiteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).AddWhiteList(ctx, req.(*AddWhiteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_DeleteWhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWhiteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).DeleteWhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.AntiBruteforce/DeleteWhiteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).DeleteWhiteList(ctx, req.(*DeleteWhiteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_AddBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlackListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).AddBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.AntiBruteforce/AddBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).AddBlackList(ctx, req.(*AddBlackListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_DeleteBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlackListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).DeleteBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcapi.AntiBruteforce/DeleteBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).DeleteBlackList(ctx, req.(*DeleteBlackListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AntiBruteforce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.AntiBruteforce",
	HandlerType: (*AntiBruteforceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckLogin",
			Handler:    _AntiBruteforce_CheckLogin_Handler,
		},
		{
			MethodName: "ResetLogin",
			Handler:    _AntiBruteforce_ResetLogin_Handler,
		},
		{
			MethodName: "AddWhiteList",
			Handler:    _AntiBruteforce_AddWhiteList_Handler,
		},
		{
			MethodName: "DeleteWhiteList",
			Handler:    _AntiBruteforce_DeleteWhiteList_Handler,
		},
		{
			MethodName: "AddBlackList",
			Handler:    _AntiBruteforce_AddBlackList_Handler,
		},
		{
			MethodName: "DeleteBlackList",
			Handler:    _AntiBruteforce_DeleteBlackList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "antibf.proto",
}
